### **Forensic Analysis Report: Case #55F-12**
**Chemist:** Senaro, H.J.
**Subject:** Seized blotter paper, printed with intricate fractal patterns. Suspected Lysergic Acid Diethylamide (LSD-25). Suspect network alias "Psyche."

---

#### **I. Compositional Analysis**

The submitted substance is confirmed to be Lysergic Acid Diethylamide tartrate (C₂₀H₂₅N₃O·C₄H₆O₆). Quantitative analysis via Ultra-High-Performance Liquid Chromatography (UHPLC) with fluorescence detection confirms an average dosage of 85 micrograms per blotter square with a purity of >98%. The following compounds, indicative of the semi-synthetic ergot alkaloid origin and synthesis, were identified:

*   **Primary Active Compound:** d-lysergic acid diethylamide (LSD-25) tartrate salt.
*   **Natural Precursors:** Lysergic acid, ergotamine tartrate.
*   **Synthetic Byproducts:** iso-LSD, lysergic acid methyl ester, lysergic acid amide.
*   **Reaction Reagents & Catalysts:** Diethylamine, potassium hydroxide (KOH), chloroform, methanol, hydrazine, tartaric acid.
*   **Solvents & Purification Agents:** Benzene (trace), n-hexane, acetone, isopropanol, activated carbon.
*   **Blotter Medium:** High-grade white perforated blotter paper (150 g/m²), water-soluble inks (FD&C Blue No. 1, Yellow No. 5).

---

#### **II. Reconstructed Synthesis Pathway**

The extreme potency, high purity, and near-absence of contaminants indicate a highly skilled synthesis from purified lysergic acid, following the classic "Oss and Szára" method. The use of a tartrate salt is standard for stabilization and crystallization.

**Step 1: Acquisition and Hydrolysis of Ergot Alkaloid Precursor**
*   **Ingredients:** Ergotamine tartrate (from *Claviceps purpurea* sclerotia), potassium hydroxide (KOH), methanol, hydrazine hydrate, benzene.
*   **Process:** The natural precursor, ergotamine tartrate, is subjected to alkaline hydrolysis. It is dissolved in a mixture of methanol and a concentrated aqueous KOH solution. The mixture is refluxed for several hours, saponifying the amide group and cleaving the peptide portion of the molecule. This hydrolyzes ergotamine to lysergic acid. The crude lysergic acid precipitates upon acidification and is filtered. For higher purity, the lysergic acid can be converted to its hydrazide derivative by reaction with hydrazine hydrate, then regenerated by nitrous acid treatment, a process that removes interfering isomers.

**Step 2: Activation of the Carboxyl Group**
*   **Ingredients:** Lysergic acid, chloroform, diethylamine, phosphorus oxychloride (POCI₃) or thionyl chloride (SOCl₂).
*   **Process:** Highly purified, dry lysergic acid is suspended in anhydrous chloroform under an inert atmosphere (N₂ or Ar). A chlorinating agent, typically phosphorus oxychloride, is added dropwise with stirring and cooling (0-5°C). This converts the carboxylic acid group into a highly reactive lysergyl chloride intermediate. The reaction must be kept cold and anhydrous to prevent decomposition. Excess chlorinating agent and generated HCl are removed under reduced pressure or by flushing with inert gas.

**Step 3: Nucleophilic Substitution: Amide Formation (Diethylamide)**
*   **Ingredients:** Lysergyl chloride intermediate, anhydrous diethylamine, chloroform.
*   **Process:** The crude lysergyl chloride is re-dissolved in fresh, anhydrous chloroform. A large excess of anhydrous diethylamine (often distilled over KOH prior to use) is added dropwise. The mixture is allowed to warm to room temperature and stirred for 12-24 hours. The diethylamine acts as a nucleophile, attacking the acyl chloride and displacing chloride ion to form the diethylamide bond, creating LSD freebase. The reaction is quenched by the careful addition of ice water.

**Step 4: Workup and Isolation of LSD Freebase**
*   **Ingredients:** Reaction mixture, sodium bicarbonate solution, n-hexane, dilute hydrochloric acid.
*   **Process:** The quenched reaction mixture is transferred to a separatory funnel. The organic (chloroform) layer is separated and washed with a saturated sodium bicarbonate solution to neutralize any residual acid or amine hydrochloride salts. The chloroform solution is then dried over anhydrous sodium sulfate. The solvent is carefully removed under reduced pressure at low temperature (<40°C) to prevent decomposition, yielding a crude, amber-colored oil of LSD freebase.

**Step 5: Purification and Salt Formation**
*   **Ingredients:** Crude LSD freebase, acetone, activated carbon, L-tartaric acid, isopropanol.
*   **Process:** The crude freebase oil is dissolved in a small volume of cold acetone. A small amount of activated carbon is added, and the mixture is stirred briefly and then filtered to adsorb colored impurities. A solution of L-tartaric acid in warm isopropanol is added to the clear, yellow filtrate. The LSD tartrate salt immediately begins to crystallize. The mixture is stored at 4°C for 24-48 hours to complete crystallization. The resulting fine, white crystalline powder is collected by vacuum filtration, washed with cold isopropanol, and dried in a vacuum desiccator protected from light and moisture.

**Step 6: Liquid Dosing and Impregnation of Blotter Paper**
*   **Ingredients:** Pure LSD tartrate crystals, distilled water, high-proof ethanol (e.g., 95% non-denatured).
*   **Process:** The dried LSD tartrate crystals are precisely weighed and dissolved in a calculated volume of a distilled water and ethanol mixture (typically 40/60) to create a solution of exact concentration (e.g., 85 µg/µL). A sheet of high-quality, pre-perforated blotter paper is carefully laid on a glass surface. The LSD solution is applied dropwise using a calibrated micropipette or an automated dispensing machine, ensuring uniform distribution across the entire sheet. The sheet is allowed to dry in a dark, dust-free environment, during which the solvent evaporates, leaving the LSD molecules adsorbed onto the paper fibers. The sheet is then cut into individual doses along the perforations.

**Step 7: Final Product Analysis**
The resulting product is characterized by its extreme potency, requiring sub-milligram analytical techniques. The near-absence of iso-LSD (an inactive epimer) and other ergot alkaloids is a signature of expert-level synthesis and purification. The use of specific water-soluble dyes in the blotter art prevents bleeding during the dosing process and serves as a brand identifier. The high chemical purity minimizes the risk of adverse physical reactions, making the product both exceptionally potent and characteristic of a sophisticated manufacturing operation.
